### ISSUE TITLE
LibreOffice gets stuck

### ISSUE THREAD

**Issue by dvandersluis** [unoconv/unoconv#189]
Sometimes the instance of LibreOffice opened by unoconv gets "stuck" (in that it doesn't so anything and doesn't close either), even though I'm using the -T (timeout) option when initializing unoconv. The unoconv process doesn't terminate either, until I kill LibreOffice.

Is there any way to detect if the listener has frozen (or whatever's actually going on), and have unoconv kill it once the timeout expires (assuming I'm not using a permanent listener, which I'm not), or at least exit with some sort of error that I could handle myself (a PID would be helpful)?

**Comment by lorenzyannick** [comment]
any news about that ?
I have the same issue and I didn't find why it happens.
Thx

**Comment by imkarthikk** [comment]
Do you think killing `soffice.bin` every time a unoconv process is starting solve this issue?

**Comment by dagwieers** [comment]
@imkarthikk Normally unoconv takes great care in killing the soffice it spawned itself for the conversion (except if we use an existing listener, or if there was another user of the running listener), so there shouldn't be a need to kill it. However, if it gets stuck and unoconv is interrupted, the started listener may still be around.

So maybe it makes sense to do it just to be sure, however the real fix is to reproduce this and open an bug in the LibreOffice bug-tracker. If it is reproducable, you may want to test if LibreOffice can handle the file properly.

**Comment by gdott9** [comment]
Hello @dagwieers ,

I have the same problem with the LibreOffice process and I have a question about the `die` method.

On [unoconv#L1304](https://github.com/unoconv/unoconv/blob/0.8.2/unoconv#L1304), `ooprc.wait()` is called.
I'm not really familiar with Python but if I understand the documentation, it will wait indefinitely for the process to end. So, if the soffice.bin process is stuck, it will never go past this line and will never call `ooprc.kill()` (or `os.kill(ooproc.pid, 9)`).

Since Python 3.3, [Popen.wait](https://docs.python.org/3.4/library/subprocess.html#subprocess.Popen.wait) has a timeout option. But to support previous version of Python, should [unoconv#L1304](https://github.com/unoconv/unoconv/blob/0.8.2/unoconv#L1304) and [unoconv#L1310](https://github.com/unoconv/unoconv/blob/0.8.2/unoconv#L1310) be replaced by something like the following lines of code ?
```python
start = time.time()
timeout = 30
while time.time() - start < timeout:
    time.sleep(0.1)
    if ooproc.poll() != None:
        break
````
With this code, it will wait and if after 30 seconds the libreoffice process is still running, it will try to kill it.

What do you think about this ?
