### ISSUE TITLE
Unoconv  : Converting html to doc  - the tables with width in percentage  are not properly displayed in the doc file  

### ISSUE THREAD

**Issue by mkaayn** [unoconv/unoconv#227]
Hello,

I try to do a conversion of a file from html to doc. In my html file I have a table with “width = 100%” and after the conversion, in the doc file, the table is not displayed on the  entire page.

My unoconv and LibreOffice versions :
unoconv 0.5
platform posix/linux2
python 2.7.3 (default, Mar 14 2014, 11:57:14)
[GCC 4.7.2]
LibreOffice 3.5

Thank you.

**Comment by dagwieers** [comment]
Please follow the information in the Troubleshooting section on the README.
Because you probably want to test at least unoconv 0.6 (or the one from the master branch) and use the latest LibreOffice (3.5 is quite old !). If the latest LibreOffice does not fix your issue, and it fails even when exporting from the LibreOffice GUI, then you may have to report your issue on the LibreOffice bug-tracker. If you do so, please add a link here to the ticket you opened in the bug-tracker so others can find a reference to it.

Thanks in advance for reporting it upstream ! :+1:

**Comment by mcmyt** [comment]
How can I build/use the unovconv from the master branch I'm having the same issue
