### ISSUE TITLE
unoconv doesn't connect another machine

### ISSUE THREAD

**Issue by Giancarlo1974** [unoconv/unoconv#492]
In the istructions i read:

This also works on a remote host:

`    unoconv --listener --server 1.2.3.4 --port 4567`

and then connect another system to convert documents:

`    unoconv --server 1.2.3.4 --port 4567`

the remote host is ok!

but the client raise:

**unoconv: Cannot find a suitable office installation on your system.**

but the suitable office is on the remote machine :-(

**Comment by regebro** [comment]
Ah, yes, but it's Libreoffice that deals with that connection. The listener/server bit it designed so that you don't have to start Libreoffice for every document you convert, but so that you can have a resident running Libreoffice to do the conversion things, not to run it on another computer. 

I tried to see if it works, and I can't get it to work. In fact, when I start the listener, according to `lsof`, the port isn't actually open.
