### ISSUE TITLE
unable to find 'uno`'' ubuntu 19.10

### ISSUE THREAD

**Issue by byteshiva** [unoconv/unoconv#526]
unable run unoconv on ubuntu 19.10, it threw the below error

```
➜  unoconv 
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named 'uno'

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

```

**Comment by m1waterman88** [comment]
Can you provide more information? Did you call the Python interpreter from the office directory in the shebang? As it stands, you should use the Python interpreter used with your office install.

**Comment by byteshiva** [comment]
> Can you provide more information? Did you call the Python interpreter from the office directory in the shebang? As it stands, you should use the Python interpreter used with your office install.

Here are the details.
```
$UNO_PATH=/usr/lib/libreoffice/program/ unoconv -f pdf some-file.odt
unoconv: Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice
ERROR: No module named 'uno'

unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

```

```
$pwd 
/usr/lib/libreoffice/program
$:/usr/lib/libreoffice/program$ ls uno*
uno  uno.bin  unoinfo  unopkg  unopkg.bin  unorc
```

**Comment by m1waterman88** [comment]
Sorry, my mind goes to Python scripts first with unoconv since that's the route I went when learning. UNO_PATH works just as well.

If you haven't read the README.md on the unoconv GitHub page, please do so. It does mention this error with possible solutions. If they don't work for you, I can take a look at the code to see what's expected. I just cloned the unoconv repo yesterday and started parsing through it.

**Comment by kjantzer** [comment]
I was seeing a similar error in my Docker container. Saw [someone else](https://github.com/thecodingmachine/gotenberg/blob/master/build/base/Dockerfile#L34) do this and it worked for me too

```
ln -s /usr/bin/python3 /usr/bin/python
```

Note: if `/usr/bin/python` already exists, run this first:
```
mv /usr/bin/python /usr/bin/python1
```

**Comment by m1waterman88** [comment]
One last check-in on this one. I haven't heard back since the original reply.

For the Docker container: If you're in a venv/container and your office install is in the system default interpreter, it's been my experience that you'll receive issues since the necessary modules can't communicate. Do you receive success outside of the container?
