### ISSUE TITLE
Unable to convert Docx to PDF in a Python script. Unsupported URL

### ISSUE THREAD

**Issue by kashaziz** [unoconv/unoconv#530]
I have installed unoconv on Ubuntu, the versions being:

unoconv 0.7
python 3.6.8 (default, Apr  9 2019, 04:59:38)
LibreOffice 6.1.6.3

To run unoconv from CLI, I have to use sudo unconv. It works and converts Docx to PDF

However, when I try to call it in a Python script, as follows, it throws an error.

```
import subprocess
import os

filename = "word (51a1dace-1d0f-4524-ac3e-4ab4633aeaa6).doc"
filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), filename)

subprocess.run(["sudo", "/usr/bin/unoconv", "-f", "pdf", filename])

```

**Error:**
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <word (51a1dace-1d0f-4524-ac3e-4ab4633aeaa6).doc>: "from LoadEnv::initializeLoading"

What could be the issue here?

**Comment by m1waterman88** [comment]
Some initial thoughts/suggestions before exploring further.

1. Have you read the README to review solutions to common issues? It's always a good place to start.
2. Since you're running a Python script, you should call the Python interpreter delivered with the office instance in a shebang.
3. Is "word (51a1dace-1d0f-4524-ac3e-4ab4633aeaa6).doc" actually the name of the file?
4. If you run the filepath portion separately, do you get the expected result (i.e., the correct path)?

**Comment by m1waterman88** [comment]
Closing issue. There is insufficient information, and there hasn't been a response.
