### ISSUE TITLE
Semicolons in command string appear to break the unoconv command under some shells

### ISSUE THREAD

**Issue by axfelix** [unoconv/unoconv#542]
Hi,

This was working for me previously I'm pretty sure but I just tried running unoconv under WSL for the first time and the process was hanging. When I tried running the unoconv command that gets sent to LibreOffice directly, I got this:

```
axfelix@shoebox:/mnt/c/Users/axfel/Desktop/objects$ /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nologo --norestore --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
^CNo command 'urp' found, did you mean:
 Command 'burp' from package 'burp' (universe)
 Command 'ur' from package 'libur-perl' (universe)
 Command 'unp' from package 'unp' (universe)
 Command 'arp' from package 'net-tools' (main)
 Command 'rup' from package 'rstat-client' (universe)
urp: command not found
StarOffice.ComponentContext: command not found
```

Looks like it's breaking on the semicolons? Is there a way to escape those upstream so that this is more environment-proof? Thanks.

**Comment by m1waterman88** [comment]
Hi,

soffice is a LibreOffice tool and not part of unoconv. If you supply the unoconv command, I may be able to help with unoconv-related issues.

More generally, though, Bash shells interpret semi-colons as breaks: a start of a new command. So the shell thinks you're calling three commands, as if you're doing this:

```
axfelix@shoebox:/mnt/c/Users/axfel/Desktop/objects$ /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nologo --norestore --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1
axfelix@shoebox:/mnt/c/Users/axfel/Desktop/objects$ urp
axfelix@shoebox:/mnt/c/Users/axfel/Desktop/objects$ StarOffice.ComponentContext
```

Since those aren't commands in your environment, Bash is trying to find package suggestions in the Ubuntu repositories.

Looks like you need quotes to enclose everything following the accept argument's equal sign.

**Comment by axfelix** [comment]
Ah, sorry, I should've clarified -- I got that after looking up the unoconv process call that appeared to be hanging in this enivronment, and trying to re-run it. The suggestion to quote everything following the equals sign worked, though, and once running the listener command manually unoconv appears to be working normally!

**Comment by m1waterman88** [comment]
No worries, and glad it worked!
